-- New records to add to Database_Relationship table to enable database export on the Collections tables.
DELETE FROM Database_Relationship WHERE Relationship_Key IN (
'SYSTEM0000000000', 'SYSTEM0000000001', 'SYSTEM0000000002', 'SYSTEM0000000003', 'SYSTEM0000000004', 'SYSTEM0000000005', 'SYSTEM0000000006', 'SYSTEM0000000007', 
'SYSTEM0000000008', 'SYSTEM0000000009', 'SYSTEM000000000A', 'SYSTEM000000000B', 'SYSTEM000000000C', 'SYSTEM000000000D', 'SYSTEM000000000E', 'SYSTEM000000000F', 
'SYSTEM000000000G', 'SYSTEM000000000H', 'SYSTEM000000000I', 'SYSTEM000000000J', 'SYSTEM000000000K', 'SYSTEM000000000L', 'SYSTEM000000000M', 'SYSTEM000000000N', 
'SYSTEM000000000O', 'SYSTEM000000000P', 'SYSTEM000000000Q', 'SYSTEM000000000R', 'SYSTEM000000000S', 'SYSTEM000000000T', 'SYSTEM000000000U', 'SYSTEM000000000V', 
'SYSTEM000000000W', 'SYSTEM000000000X', 'SYSTEM000000000Y', 'SYSTEM000000000Z', 'SYSTEM0000000010', 'SYSTEM0000000011', 'SYSTEM0000000012', 'SYSTEM0000000013', 
'SYSTEM0000000014', 'SYSTEM0000000015', 'SYSTEM0000000016', 'SYSTEM0000000017', 'SYSTEM0000000018', 'SYSTEM0000000019', 'SYSTEM000000001A', 'SYSTEM000000001B', 
'SYSTEM000000001C', 'SYSTEM000000001D', 'SYSTEM000000001E', 'SYSTEM000000001F', 'SYSTEM000000001G', 'SYSTEM000000001H', 'SYSTEM000000001I', 'SYSTEM000000001J', 
'SYSTEM000000001K', 'SYSTEM000000001L', 'SYSTEM000000001M', 'SYSTEM000000001N', 'SYSTEM000000001O', 'SYSTEM000000001P', 'SYSTEM000000001Q', 'SYSTEM000000001R', 
'SYSTEM000000001S', 'SYSTEM000000001T', 'SYSTEM000000001U', 'SYSTEM000000001V', 'SYSTEM000000001W', 'SYSTEM000000001X', 'SYSTEM000000001Y', 'SYSTEM000000001Z', 
'SYSTEM0000000020', 'SYSTEM0000000021', 'SYSTEM0000000022', 'SYSTEM0000000023', 'SYSTEM0000000024', 'SYSTEM0000000025', 'SYSTEM0000000026', 'SYSTEM0000000027', 
'SYSTEM0000000028', 'SYSTEM0000000029', 'SYSTEM000000002A', 'SYSTEM000000002B', 'SYSTEM000000002C', 'SYSTEM000000002D', 'SYSTEM000000002E', 'SYSTEM000000002F', 
'SYSTEM000000002G', 'SYSTEM000000002H', 'SYSTEM000000002I', 'SYSTEM000000002J', 'SYSTEM000000002K', 'SYSTEM000000002L', 'SYSTEM000000002M', 'SYSTEM000000002N', 
'SYSTEM000000002O', 'SYSTEM000000002P', 'SYSTEM000000002Q', 'SYSTEM000000002R', 'SYSTEM000000002S', 'SYSTEM000000002T', 'SYSTEM000000002U')

INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000001', 'Collection_UnitStore', 'Collection_Unit', 'Collection_Unit_Key', 'Store', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000002', 'StoreCollection_UnitCurrent', 'Store', 'Collection_Unit_Key', 'Collection_Unit', 'Current_Container_Collection_Unit_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000003', 'StoreCollection_UnitUsual', 'Store', 'Collection_Unit_Key', 'Collection_Unit', 'Usual_Container_Collection_Unit_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000004', 'ConceptStore', 'Concept', 'Concept_Key', 'Store', 'Ctore_Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000005', 'Collection_UnitCollection', 'Collection_Unit', 'Collection_Unit_Key', 'Collection', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000006', 'NAMECollection', 'NAME', 'NAME_KEY', 'Collection', 'Assembler_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000007', 'ConceptCollection', 'Concept', 'Concept_Key', 'Collection', 'Risk_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000008', 'CollectionSpecimen_Unit', 'Collection', 'Collection_Unit_Key', 'Specimen_Unit', 'Parent_Collection_Collection_Unit_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000009', 'Collection_UnitSpecimen_Unit', 'Collection_Unit', 'Collection_Unit_Key', 'Specimen_Unit', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000A', 'Specimen_UnitTAXON_DETERMINATION', 'Specimen_Unit', 'Collection_Unit_Key', 'TAXON_DETERMINATION', 'Specimen_Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000B', 'Specimen_UnitSpecimen_Field_Data', 'Specimen_Unit', 'Collection_Unit_Key', 'Specimen_Field_Data', 'Collection_Unit_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000C', 'Specimen_UnitCollection_Unit_Material', 'Specimen_Unit', 'Collection_Unit_Key', 'Collection_Unit_Material', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000D', 'Specimen_UnitDetermination', 'Specimen_Unit', 'Collection_Unit_Key', 'Determination', 'Specimen_Collection_Unit_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000E', 'OccurrenceDetermination', 'Occurrence', 'Occurrence_Key', 'Determination', 'Occurrence_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000F', 'ConceptDeterminationConcept', 'Concept', 'Concept_Key', 'Determination', 'Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000G', 'ConceptDeterminationNomenclature', 'Concept', 'Concept_Key', 'Determination', 'Nomenclature_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000H', 'INDIVIDUALDetermination', 'INDIVIDUAL', 'NAME_KEY', 'Determination', 'Determiner_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000I', 'DETERMINATION_TYPEDetermination', 'DETERMINATION_TYPE', 'DETERMINATION_TYPE_KEY', 'Determination', 'Determination_Type_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000J', 'DETERMINER_ROLEDetermination', 'DETERMINER_ROLE', 'DETERMINER_ROLE_KEY', 'Determination', 'Determiner_Role_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000K', 'ConceptSpecimen_Unit', 'Concept', 'Concept_Key', 'Specimen_Unit', 'Specimen_Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000L', 'TAXON_OCCURRENCESpecimen_Field_Data', 'TAXON_OCCURRENCE', 'TAXON_OCCURRENCE_KEY', 'Specimen_Field_Data', 'Taxon_Occurrence_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000M', 'OccurrenceSpecimen_Field_Data', 'Occurrence', 'Occurrence_Key', 'Specimen_Field_Data', 'Occurrence_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000N', 'SAMPLEOccurrence', 'SAMPLE', 'SAMPLE_KEY', 'Occurrence', 'Sample_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000O', 'ConceptOccurrence', 'Concept', 'Concept_Key', 'Occurrence', 'Record_Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000P', 'OccurrenceOccurrence_Data', 'Occurrence', 'Occurrence_Key', 'Occurrence_Data', 'Occurrence_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000Q', 'OccurrenceOccurrence_Relation', 'Occurrence', 'Occurrence_Key', 'Occurrence_Relation', 'From_Occurrence_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000R', 'ConceptOccurrence_DataMethod', 'Concept', 'Concept_Key', 'Occurrence_Data', 'Method_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000S', 'ConceptOccurrence_DataParameter', 'Concept', 'Concept_Key', 'Occurrence_Data', 'Parameter_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000T', 'ConceptOccurrence_DataUnit', 'Concept', 'Concept_Key', 'Occurrence_Data', 'Unit_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000U', 'ConceptCollection_Unit_MaterialMaterial', 'Concept', 'Concept_Key', 'Collection_Unit_Material', 'Material_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000V', 'ConceptCollection_Unit_MaterialUnit', 'Concept', 'Concept_Key', 'Collection_Unit_Material', 'Unit_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000W', 'Collection_UnitCollection_Unit_Check', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Check', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000X', 'Collection_UnitCollection_Unit_Data', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Data', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000Y', 'Collection_UnitCollection_Unit_Enquiry', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Enquiry', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000000Z', 'Collection_UnitCollection_Unit_History', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_History', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000010', 'Collection_UnitCollection_Unit_Name', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Name', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000011', 'Collection_UnitCollection_Unit_Number', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Number', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000012', 'Collection_UnitCollection_Unit_Process', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Process', 'Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000013', 'Collection_UnitCollection_Unit_Task', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Task', 'Collection_Unit_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000014', 'Collection_UnitCollection_Unit_Relation', 'Collection_Unit', 'Collection_Unit_Key', 'Collection_Unit_Relation', 'From_Collection_Unit_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000015', 'INDIVIDUALCollection_Unit_History', 'INDIVIDUAL', 'NAME_KEY', 'Collection_Unit_History', 'Source_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000016', 'NAMECollection_Unit_Name', 'NAME', 'NAME_KEY', 'Collection_Unit_Name', 'Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000017', 'ConceptCollection_Unit_Name', 'Concept', 'Concept_Key', 'Collection_Unit_Name', 'Relation_Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000018', 'INDIVIDUALCollection_Unit_Process', 'INDIVIDUAL', 'NAME_KEY', 'Collection_Unit_Process', 'Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000019', 'ConceptCollection_Unit_Process', 'Concept', 'Concept_Key', 'Collection_Unit_Process', 'Process_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001A', 'ConceptCollection_Unit_Number', 'Concept', 'Concept_Key', 'Collection_Unit_Number', 'Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001B', 'ConceptCollection_Unit_DataMethod', 'Concept', 'Concept_Key', 'Collection_Unit_Data', 'Method_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001C', 'ConceptCollection_Unit_DataParameter', 'Concept', 'Concept_Key', 'Collection_Unit_Data', 'Parameter_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001D', 'ConceptCollection_Unit_DataUnit', 'Concept', 'Concept_Key', 'Collection_Unit_Data', 'Unit_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001E', 'EnquiryCollection_Unit_Enquiry', 'Enquiry', 'Enquiry_Key', 'Collection_Unit_Enquiry', 'Enquiry_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001F', 'NAMEEnquiry', 'NAME', 'NAME_KEY', 'Enquiry', 'Answered_By_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001G', 'INDIVIDUALEnquiry', 'INDIVIDUAL', 'NAME_KEY', 'Enquiry', 'Enquirer_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001H', 'ConceptEnquiryMethod', 'Concept', 'Concept_Key', 'Enquiry', 'Enquiry_Method_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001I', 'ConceptEnquiryType', 'Concept', 'Concept_Key', 'Enquiry', 'Enquiry_Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001J', 'EnquiryEnquiry_Concept', 'Enquiry', 'Enquiry_Key', 'Enquiry_Concept', 'Enquiry_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001K', 'ConceptEnquiry_Concept', 'Concept', 'Concept_Key', 'Enquiry_Concept', 'Concept_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001L', 'Conservation_CheckCollection_Unit_Check', 'Conservation_Check', 'Conservation_Check_Key', 'Collection_Unit_Check', 'Conservation_Check_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001M', 'NAMEConservation_Check', 'NAME', 'NAME_KEY', 'Conservation_Check', 'Checked_By_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001N', 'ConceptConservation_CheckCondition', 'Concept', 'Concept_Key', 'Conservation_Check', 'Condition_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001O', 'ConceptConservation_CheckType', 'Concept', 'Concept_Key', 'Conservation_Check', 'Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001P', 'Conservation_CheckConservation_Task', 'Conservation_Check', 'Conservation_Check_Key', 'Conservation_Task', 'Conservation_Check_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001Q', 'INDIVIDUALConservation_Task', 'INDIVIDUAL', 'NAME_KEY', 'Conservation_Task', 'Identifier_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001R', 'ConceptConservation_Task', 'Concept', 'Concept_Key', 'Conservation_Task', 'Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001S', 'Conservation_TaskCollection_Unit_Task', 'Conservation_Task', 'Conservation_Task_Key', 'Collection_Unit_Task', 'Conservation_Task_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001T', 'Conservation_JobConservation_Task', 'Conservation_Job', 'Conservation_Job_Key', 'Conservation_Task', 'Conservation_Job_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001U', 'Conservation_JobConservation_Job_Staff', 'Conservation_Job', 'Conservation_Job_Key', 'Conservation_Job_Staff', 'Conservation_Job_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001V', 'Conservation_JobConservation_Job_Material', 'Conservation_Job', 'Conservation_Job_Key', 'Conservation_Job_Material', 'Conservation_Job_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001W', 'INDIVIDUALConservation_Job_Staff', 'INDIVIDUAL', 'NAME_KEY', 'Conservation_Job_Staff', 'Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001X', 'ConceptConservation_Job_MaterialMaterial', 'Concept', 'Concept_Key', 'Conservation_Job_Material', 'Material_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001Y', 'ConceptConservation_Job_MaterialUnit', 'Concept', 'Concept_Key', 'Conservation_Job_Material', 'Unit_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000001Z', 'ConceptConcept', 'Concept', 'Concept_Key', 'Concept', 'Name_Type_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000020', 'ConceptConcept_Lineage', 'Concept', 'Concept_Key', 'Concept_Lineage', 'Concept_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000021', 'ConceptConcept_DesignationConcept', 'Concept', 'Concept_Key', 'Concept_Designation', 'Concept_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000022', 'ConceptConcept_DesignationDesignation', 'Concept', 'Concept_Key', 'Concept_Designation', 'Designation_Type_Concept_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000023', 'ConceptSpecimen_Label', 'Concept', 'Concept_Key', 'Specimen_Label', 'Confidence_Concept_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000024', 'INDIVIDUALSpecimen_Label', 'INDIVIDUAL', 'NAME_KEY', 'Specimen_Label', 'Author_Name_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000025', 'LanguageSpecimen_Label', 'Language', 'Language_Key', 'Specimen_Label', 'Translated_Language_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000026', 'LanguageLocal_Domain', 'Language', 'Language_Key', 'Local_Domain', 'Language_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000027', 'LanguageTerm', 'Language', 'Language_Key', 'Term', 'Language_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000028', 'LanguageThesaurus_Fact', 'Language', 'Language_Key', 'Thesaurus_Fact', 'Language_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM0000000029', 'TermTerm_Version', 'Term', 'Term_Key', 'Term_Version', 'Term_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002A', 'TermConcept', 'Term', 'Term_Key', 'Concept', 'Term_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002B', 'MeaningTerm_Version', 'Meaning', 'Meaning_Key', 'Term_Version', 'Meaning_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002C', 'MeaningThesaurus_Fact', 'Meaning', 'Meaning_Key', 'Thesaurus_Fact', 'Meaning_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002D', 'MeaningConcept', 'Meaning', 'Meaning_Key', 'Concept', 'Meaning_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002E', 'MeaningMeaning_Relation', 'Meaning', 'Meaning_Key', 'Meaning_Relation', 'From_Meaning_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002F', 'Local_DomainDomain_Hyperlink', 'Local_Domain', 'Local_Domain_Key', 'Domain_Hyperlink', 'Local_Domain_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002G', 'Local_DomainConcept_Group', 'Local_Domain', 'Local_Domain_Key', 'Concept_Group', 'Local_Domain_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002H', 'DomainLocal_Domain', 'Domain', 'Domain_Key', 'Local_Domain', 'Domain_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002I', 'DomainConcept_Rank', 'Domain', 'Domain_Key', 'Concept_Rank', 'Domain_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002J', 'Subject_AreaDomain', 'Subject_Area', 'Subject_Area_Key', 'Domain', 'Subject_Area_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002K', 'ConceptConcept_History', 'Concept', 'Concept_Key', 'Concept_History', 'Concept_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002L', 'Concept_Group_VersionConcept_History', 'Concept_Group_Version', 'Concept_Group_Version_Key', 'Concept_History', 'Concept_Group_Version_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002M', 'Concept_GroupConcept_Group_Version', 'Concept_Group', 'Concept_Group_Key', 'Concept_Group_Version', 'Concept_Group_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002N', 'ConceptConcept_Relation', 'Concept', 'Concept_Key', 'Concept_Relation', 'From_Concept_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002O', 'Thesaurus Relation_TypeConcept_Relation', 'Thesaurus Relation_Type', 'Thesaurus_Relation_Type_Key', 'Concept_Relation', 'Thesaurus_Relation_Type_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002P', 'Thesaurus Relation_TypeMeaning_Relation', 'Thesaurus Relation_Type', 'Thesaurus_Relation_Type_Key', 'Meaning_Relation', 'Thesaurus_Relation_Type_Key', 1, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002Q', 'Thesaurus Relation_TypeOccurrence_Relation', 'Thesaurus Relation_Type', 'Thesaurus_Relation_Type_Key', 'Occurrence_Relation', 'Thesaurus_Relation_Type_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002R', 'Thesaurus Relation_TypeThesaurus_Relation_Type_Usage', 'Thesaurus Relation_Type', 'Thesaurus_Relation_Type_Key', 'Thesaurus_Relation_Type_Usage', 'Thesaurus_Relation_Type_Key', 0, 1)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002S', 'Semantic_RelationThesaurus_Relation_Type', 'Semantic_Relation', 'Semantic_Relation_Key', 'Thesaurus_Relation_Type', 'Semantic_Relation_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002T', 'Organisation_DepartmentINDIVIDUAL', 'Organisation_Department', 'Name_Key', 'INDIVIDUAL', 'Organisation_Department_Key', 1, 0)
INSERT INTO Database_Relationship (Relationship_Key, Relationship_Name, Master_Table, Master_Field, Detail_Table,  Detail_Field, Follow_Up, Follow_Down) 
VALUES('SYSTEM000000002U', 'NAMEOrganisation_Department', 'NAME', 'NAME_KEY', 'Organisation_Department', 'Name_Key', 1, 0)
